### ISSUE TITLE
Remove text from the top

### ISSUE THREAD

**Issue by OJCubing** [simonkellly/scramble-organizer#2]
Please add functionality that removes all the text at the top, so I can easily Ctrl+A Ctrl+C Alt+Tab Ctrl+V.
If really needs be, leave in the competition name and just cut out the rest of the delegate wording.

**Comment by OJCubing** [comment]
P.S. I gave it a star like you asked :)

**Comment by simonkellly** [comment]
I will do this, I will also add dropping the whole txt file straight onto the window
